### ISSUE TITLE
Missing util functions in multi-lingual exercise 

### ISSUE THREAD

**Issue by rn-v** [neubig/lowresource-nlp-bootcamp-2020#1]
Thanks for the great material!

The mBERT notebook in the multi-lingual exercise imports a few functions from utils which are missing.

**Comment by chan0park** [comment]
Hi @keratin7, as you pointed out, `utils.py` was not up-to-date. I just sent out a new pull request, so it should be updated very soon! Thanks.

**Comment by rn-v** [comment]
Great. Thanks @chan0park!
